-- Native geometry assertions, not a substitute for mouse/monitor acceptance.
assert(getProfileName()=='AardwolfToolboxSettingsTest','Use the disposable test profile')
assert(not select(3,getConnectionInfo()),'Disconnect the disposable profile first')
assert(AardwolfToolboxAcceptance,'Run native_foundation.lua first')
assert(AardwolfToolboxWorkspaceAcceptance,'Run native_workspace.lua first')
local t=AardwolfToolbox
local previous=t.views.mode('abilities')
assert(t.views.setMode('abilities','floating'))
assert(t.views.open('abilities'))
local name='AardwolfToolbox.views.'..getProfileName()..'.abilities'
local window=assert(Geyser.parentWindows[name],'External window missing')
window:resize(640,520)
tempTimer(0.1,function()
  local ok,err=pcall(function()
    assert(getProfileName()=='AardwolfToolboxSettingsTest' and not select(3,getConnectionInfo()))
    local root=assert(window.windowList['AardwolfToolbox.browser.abilities'])
    local footer=assert(root.windowList['AardwolfToolbox.browser.abilities.previous'])
    local height=t.ui.metrics().height
    assert(math.abs(root:get_height()-520)<2,'External content did not resize')
    assert(math.abs(footer:get_y()-root:get_y()-(520-height))<2,'Footer did not reflow')
    t.views.menu('abilities')
    assert(window.windowList['AardwolfToolbox.views.menu'],'Menu is outside its external window')
  end)
  t.views.closeMenu()
  local restored,why=t.views.setMode('abilities',previous)
  assert(restored,why)
  assert(ok,err)
  echo('WORKSPACE_GEOMETRY: native resize event, footer reflow and external menu ownership passed.\n')
end)
