assert(getProfileName() == "AardwolfToolboxTerrainTest", "Wrong profile")
local function packet(num, terrain)
  gmcp = {room = {info = {num = num, name = terrain or "No terrain",
    zone = "terrain-test", exits = {}, terrain = terrain}}}
  raiseEvent("gmcp.room.info")
  assert(AardwolfToolbox.mapper.enabled, AardwolfToolbox.mapper.last)
  return getRoomIDbyHash("AardwolfToolbox:aardwolf:vnum:" .. num)
end
local forest = packet(993001, "forest")
local water = packet(993002, "water")
local desert = packet(993003, "desert")
local unknown = packet(993004, "crystal palace")
local colors = getCustomEnvColorTable()
assert(getRoomUserData(forest, "AardwolfToolbox:terrain") == "forest")
assert(colors[getRoomEnv(forest)][2] == 139)
assert(colors[getRoomEnv(water)][3] == 220)
assert(colors[getRoomEnv(desert)][1] == 225)
assert(colors[getRoomEnv(unknown)][1] == 145)
local env = getRoomEnv(forest)
packet(993001, nil)
assert(getRoomEnv(forest) == env)
packet(993001, "water")
assert(getRoomEnv(forest) == getRoomEnv(water))
packet(993001, "forest")
setRoomEnv(unknown, 77)
packet(993004, "water")
assert(getRoomEnv(unknown) == 77)
assert(getRoomUserData(unknown, "AardwolfToolbox:terrain") == "water")
-- Arrange the synthetic preview, without changing the mapper's layout logic.
setRoomCoordinates(forest, -2, 0, 0)
setRoomCoordinates(water, 0, 0, 0)
setRoomCoordinates(desert, 2, 0, 0)
setRoomCoordinates(unknown, 0, -2, 0)
centerview(unknown)
updateMap()
assert(saveMap(getMudletHomeDir() .. "/terrain-acceptance.dat"))
echo("NATIVE_TERRAIN_ACCEPTANCE_PASSED\n")
